// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "github.com/peczenyj/structalign/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// Aligner is an autogenerated mock type for the Aligner type
type Aligner struct {
	mock.Mock
}

type Aligner_Expecter struct {
	mock *mock.Mock
}

func (_m *Aligner) EXPECT() *Aligner_Expecter {
	return &Aligner_Expecter{mock: &_m.Mock}
}

// Findings provides a mock function with given fields: t, patterns, keepTags
func (_m *Aligner) Findings(t common.Target, patterns []string, keepTags bool) ([]common.Finding, error) {
	ret := _m.Called(t, patterns, keepTags)

	if len(ret) == 0 {
		panic("no return value specified for Findings")
	}

	var r0 []common.Finding
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Target, []string, bool) ([]common.Finding, error)); ok {
		return rf(t, patterns, keepTags)
	}
	if rf, ok := ret.Get(0).(func(common.Target, []string, bool) []common.Finding); ok {
		r0 = rf(t, patterns, keepTags)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Finding)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Target, []string, bool) error); ok {
		r1 = rf(t, patterns, keepTags)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Aligner_Findings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Findings'
type Aligner_Findings_Call struct {
	*mock.Call
}

// Findings is a helper method to define mock.On call
//   - t common.Target
//   - patterns []string
//   - keepTags bool
func (_e *Aligner_Expecter) Findings(t interface{}, patterns interface{}, keepTags interface{}) *Aligner_Findings_Call {
	return &Aligner_Findings_Call{Call: _e.mock.On("Findings", t, patterns, keepTags)}
}

func (_c *Aligner_Findings_Call) Run(run func(t common.Target, patterns []string, keepTags bool)) *Aligner_Findings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Target), args[1].([]string), args[2].(bool))
	})
	return _c
}

func (_c *Aligner_Findings_Call) Return(_a0 []common.Finding, _a1 error) *Aligner_Findings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Aligner_Findings_Call) RunAndReturn(run func(common.Target, []string, bool) ([]common.Finding, error)) *Aligner_Findings_Call {
	_c.Call.Return(run)
	return _c
}

// NewAligner creates a new instance of Aligner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAligner(t interface {
	mock.TestingT
	Cleanup(func())
}) *Aligner {
	mock := &Aligner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
