// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "github.com/peczenyj/structalign/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// Inspector is an autogenerated mock type for the Inspector type
type Inspector struct {
	mock.Mock
}

type Inspector_Expecter struct {
	mock *mock.Mock
}

func (_m *Inspector) EXPECT() *Inspector_Expecter {
	return &Inspector_Expecter{mock: &_m.Mock}
}

// Layouts provides a mock function with given fields: t, opts
func (_m *Inspector) Layouts(t common.Target, opts common.Options) []common.Layout {
	ret := _m.Called(t, opts)

	if len(ret) == 0 {
		panic("no return value specified for Layouts")
	}

	var r0 []common.Layout
	if rf, ok := ret.Get(0).(func(common.Target, common.Options) []common.Layout); ok {
		r0 = rf(t, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Layout)
		}
	}

	return r0
}

// Inspector_Layouts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Layouts'
type Inspector_Layouts_Call struct {
	*mock.Call
}

// Layouts is a helper method to define mock.On call
//   - t common.Target
//   - opts common.Options
func (_e *Inspector_Expecter) Layouts(t interface{}, opts interface{}) *Inspector_Layouts_Call {
	return &Inspector_Layouts_Call{Call: _e.mock.On("Layouts", t, opts)}
}

func (_c *Inspector_Layouts_Call) Run(run func(t common.Target, opts common.Options)) *Inspector_Layouts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(common.Target), args[1].(common.Options))
	})
	return _c
}

func (_c *Inspector_Layouts_Call) Return(_a0 []common.Layout) *Inspector_Layouts_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Inspector_Layouts_Call) RunAndReturn(run func(common.Target, common.Options) []common.Layout) *Inspector_Layouts_Call {
	_c.Call.Return(run)
	return _c
}

// NewInspector creates a new instance of Inspector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewInspector(t interface {
	mock.TestingT
	Cleanup(func())
}) *Inspector {
	mock := &Inspector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
