// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	common "github.com/peczenyj/structalign/pkg/common"
	mock "github.com/stretchr/testify/mock"
)

// Loader is an autogenerated mock type for the Loader type
type Loader struct {
	mock.Mock
}

type Loader_Expecter struct {
	mock *mock.Mock
}

func (_m *Loader) EXPECT() *Loader_Expecter {
	return &Loader_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: patterns
func (_m *Loader) Load(patterns ...string) ([]common.Target, error) {
	_va := make([]interface{}, len(patterns))
	for _i := range patterns {
		_va[_i] = patterns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 []common.Target
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) ([]common.Target, error)); ok {
		return rf(patterns...)
	}
	if rf, ok := ret.Get(0).(func(...string) []common.Target); ok {
		r0 = rf(patterns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Target)
		}
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(patterns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Loader_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type Loader_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - patterns ...string
func (_e *Loader_Expecter) Load(patterns ...interface{}) *Loader_Load_Call {
	return &Loader_Load_Call{Call: _e.mock.On("Load",
		append([]interface{}{}, patterns...)...)}
}

func (_c *Loader_Load_Call) Run(run func(patterns ...string)) *Loader_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *Loader_Load_Call) Return(_a0 []common.Target, _a1 error) *Loader_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Loader_Load_Call) RunAndReturn(run func(...string) ([]common.Target, error)) *Loader_Load_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoader creates a new instance of Loader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *Loader {
	mock := &Loader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
