package layout_test

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/peczenyj/structalign/internal/layout"
	"github.com/peczenyj/structalign/internal/testutil"
	"github.com/peczenyj/structalign/pkg/common"
)

func TestLayoutsSkipsGenerated(t *testing.T) {
	src := "// Code generated by tool. DO NOT EDIT.\n\npackage sample\n\ntype Mixed struct {\n\tA bool\n\tB int64\n\tC bool\n}\n"
	tgt := testutil.Target(t, src)

	assert.Empty(t, layout.New().Layouts(tgt, common.Options{Patterns: []string{"Mixed"}}),
		"generated structs are skipped by default")

	got := layout.New().Layouts(tgt, common.Options{Patterns: []string{"Mixed"}, IncludeGenerated: true})
	require.Len(t, got, 1, "IncludeGenerated re-includes them")
}
