package layout_test

import (
	"go/ast"
	"go/token"
	"go/types"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/peczenyj/structalign/internal/layout"
	"github.com/peczenyj/structalign/internal/sizes"
	"github.com/peczenyj/structalign/internal/testutil"
	"github.com/peczenyj/structalign/pkg/common"
)

func TestLayoutsFindsLocalStructs(t *testing.T) {
	const src = `package sample
func Foo() {
	type Local struct {
		A bool
		B int64
	}
	_ = Local{}
}
`
	tgt := testutil.Target(t, src)
	ls := layout.New().Layouts(tgt, common.Options{})

	found := false
	for _, l := range ls {
		if l.Name == "Local" {
			found = true
		}
	}
	assert.True(t, found, "Local struct inside function should be found in -inspect mode")
}

func TestLayoutsEdgeCases(t *testing.T) {
	// Nil target
	assert.Nil(t, layout.New().Layouts(common.Target{}, common.Options{}))

	// Non-struct named type
	const src = `package sample
type Foo int
`
	tgt := testutil.Target(t, src)
	ls := layout.New().Layouts(tgt, common.Options{})
	assert.Empty(t, ls, "should not report non-struct types")
}

func TestLayoutsSignaturesWithTypeParams(t *testing.T) {
	const src = `package sample
import "io"
type Generic[T any] struct {
	F1 func(T) T
	F2 func() T
	F3 func(T)
	W io.Writer
	S struct { A T } // anonymous struct
}
`
	tgt := testutil.Target(t, src)
	ls := layout.New().Layouts(tgt, common.Options{})
	assert.NotEmpty(t, ls)
	assert.Equal(t, "T=any", ls[0].Fields[0].Assume)
	assert.Equal(t, "T=any", ls[0].Fields[1].Assume)
	assert.Equal(t, "T=any", ls[0].Fields[2].Assume)
}

func TestLayoutsComplexTypes(t *testing.T) {
	const src = `package sample
type Generic[T any, K comparable, V any] struct {
	M map[K]V
	C chan T
	A [10]T
	P *Generic[T, K, V] // recursion
}
type Wrapper[T any] struct {
	G Generic[T, string, int] // nested generic
}
`
	tgt := testutil.Target(t, src)
	ls := layout.New().Layouts(tgt, common.Options{})
	assert.NotEmpty(t, ls)
}

func TestLayoutsGenerated(t *testing.T) {
	const src = "// Code generated by tool. DO NOT EDIT.\npackage sample\ntype Foo struct { A int }"
	tgt := testutil.Target(t, src)
	ls := layout.New().Layouts(tgt, common.Options{IncludeGenerated: false})
	assert.Empty(t, ls, "should skip generated file")
}

func TestLayoutsSkipCachePadded(t *testing.T) {
	// Programmatically build a struct with CacheLinePad to avoid real imports.
	cpuPkg := types.NewPackage("golang.org/x/sys/cpu", "cpu")
	padNamed := types.NewNamed(
		types.NewTypeName(token.NoPos, cpuPkg, "CacheLinePad", nil),
		types.NewStruct(nil, nil), nil)

	field := types.NewField(token.NoPos, cpuPkg, "_", padNamed, false)
	st := types.NewStruct([]*types.Var{field}, nil)

	pkg := types.NewPackage("pkg", "pkg")
	tn := types.NewTypeName(token.NoPos, pkg, "Padded", nil)
	_ = types.NewNamed(tn, st, nil)

	info := &types.Info{
		Defs: map[*ast.Ident]types.Object{
			{Name: "Padded"}: tn,
		},
	}

	tgt := common.Target{
		Types:     pkg,
		TypesInfo: info,
		Sizes:     sizes.New(types.SizesFor("gc", "amd64")),
	}

	ls := layout.New().Layouts(tgt, common.Options{SkipCachePadded: true})
	assert.Empty(t, ls, "should skip cache-padded struct")
}
