---
issue-845-fix: true
resolve-type-alias: false
quiet: false
disable-version-string: true
dir: "internal/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/peczenyj/structalign/pkg/common:
    interfaces:
      Loader:
      Aligner:
      Inspector:
