// Code generated by "enumer -type=Colorize -text -transform=lower -trimprefix=Colorize -pflag.value"; DO NOT EDIT.

package common

import (
	"fmt"
	"strings"
)

const _ColorizeName = "autoalwaysnever"

var _ColorizeIndex = [...]uint8{0, 4, 10, 15}

const _ColorizeLowerName = "autoalwaysnever"

func (i Colorize) String() string {
	if i >= Colorize(len(_ColorizeIndex)-1) {
		return fmt.Sprintf("Colorize(%d)", i)
	}
	return _ColorizeName[_ColorizeIndex[i]:_ColorizeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColorizeNoOp() {
	var x [1]struct{}
	_ = x[ColorizeAuto-(0)]
	_ = x[ColorizeAlways-(1)]
	_ = x[ColorizeNever-(2)]
}

var _ColorizeValues = []Colorize{ColorizeAuto, ColorizeAlways, ColorizeNever}

var _ColorizeNameToValueMap = map[string]Colorize{
	_ColorizeName[0:4]:        ColorizeAuto,
	_ColorizeLowerName[0:4]:   ColorizeAuto,
	_ColorizeName[4:10]:       ColorizeAlways,
	_ColorizeLowerName[4:10]:  ColorizeAlways,
	_ColorizeName[10:15]:      ColorizeNever,
	_ColorizeLowerName[10:15]: ColorizeNever,
}

var _ColorizeNames = []string{
	_ColorizeName[0:4],
	_ColorizeName[4:10],
	_ColorizeName[10:15],
}

// ColorizeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColorizeString(s string) (Colorize, error) {
	if val, ok := _ColorizeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColorizeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Colorize values", s)
}

// ColorizeValues returns all values of the enum
func ColorizeValues() []Colorize {
	return _ColorizeValues
}

// ColorizeStrings returns a slice of all String values of the enum
func ColorizeStrings() []string {
	strs := make([]string, len(_ColorizeNames))
	copy(strs, _ColorizeNames)
	return strs
}

// IsAColorize returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Colorize) IsAColorize() bool {
	for _, v := range _ColorizeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Colorize
func (i Colorize) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Colorize
func (i *Colorize) UnmarshalText(text []byte) error {
	var err error
	*i, err = ColorizeString(string(text))
	return err
}

// Set allows flag and pflag libraries to set a value dynamically.
func (i *Colorize) Set(value string) error {
	var err error
	*i, err = ColorizeString(value)
	return err
}

// Type returns a string that represents all possible values to this type joined by '|'.
func (Colorize) Type() string {
	return strings.Join(_ColorizeNames, "|")
}
