package common

//go:generate go tool enumer -type=DiffStyle -text -transform=lower -trimprefix=Diff

// DiffStyle selects how a Finding is rendered. The String/parse/text-marshal
// helpers are generated by enumer (see diffstyle_enumer.go); the names map to
// "unified", "side", "none" via -trimprefix=Diff -transform=lower.
type DiffStyle uint8

const (
	DiffUnified DiffStyle = iota
	DiffSide
	DiffNone
)

// Set implements flag.Value, parsing a style name (e.g. "side") into the
// receiver. enumer v1.6.1 has no flag.Value generator, so this small adapter
// delegates to the generated parser; String() is generated by enumer.
func (i *DiffStyle) Set(s string) error {
	v, err := DiffStyleString(s)
	if err != nil {
		return err
	}
	*i = v
	return nil
}
