// Code generated by "enumer -type=DiffStyle -text -transform=lower -trimprefix=Diff -pflag.value"; DO NOT EDIT.

package common

import (
	"fmt"
	"strings"
)

const _DiffStyleName = "unifiedsidenone"

var _DiffStyleIndex = [...]uint8{0, 7, 11, 15}

const _DiffStyleLowerName = "unifiedsidenone"

func (i DiffStyle) String() string {
	if i >= DiffStyle(len(_DiffStyleIndex)-1) {
		return fmt.Sprintf("DiffStyle(%d)", i)
	}
	return _DiffStyleName[_DiffStyleIndex[i]:_DiffStyleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DiffStyleNoOp() {
	var x [1]struct{}
	_ = x[DiffUnified-(0)]
	_ = x[DiffSide-(1)]
	_ = x[DiffNone-(2)]
}

var _DiffStyleValues = []DiffStyle{DiffUnified, DiffSide, DiffNone}

var _DiffStyleNameToValueMap = map[string]DiffStyle{
	_DiffStyleName[0:7]:        DiffUnified,
	_DiffStyleLowerName[0:7]:   DiffUnified,
	_DiffStyleName[7:11]:       DiffSide,
	_DiffStyleLowerName[7:11]:  DiffSide,
	_DiffStyleName[11:15]:      DiffNone,
	_DiffStyleLowerName[11:15]: DiffNone,
}

var _DiffStyleNames = []string{
	_DiffStyleName[0:7],
	_DiffStyleName[7:11],
	_DiffStyleName[11:15],
}

// DiffStyleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DiffStyleString(s string) (DiffStyle, error) {
	if val, ok := _DiffStyleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DiffStyleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DiffStyle values", s)
}

// DiffStyleValues returns all values of the enum
func DiffStyleValues() []DiffStyle {
	return _DiffStyleValues
}

// DiffStyleStrings returns a slice of all String values of the enum
func DiffStyleStrings() []string {
	strs := make([]string, len(_DiffStyleNames))
	copy(strs, _DiffStyleNames)
	return strs
}

// IsADiffStyle returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DiffStyle) IsADiffStyle() bool {
	for _, v := range _DiffStyleValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for DiffStyle
func (i DiffStyle) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for DiffStyle
func (i *DiffStyle) UnmarshalText(text []byte) error {
	var err error
	*i, err = DiffStyleString(string(text))
	return err
}

// Set allows flag and pflag libraries to set a value dynamically.
func (i *DiffStyle) Set(value string) error {
	var err error
	*i, err = DiffStyleString(value)
	return err
}

// Type returns a string that represents all possible values to this type joined by '|'.
func (DiffStyle) Type() string {
	return strings.Join(_DiffStyleNames, "|")
}
