package structfilter_test

import (
	"go/token"
	"go/types"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/peczenyj/structalign/internal/structfilter"
	"github.com/peczenyj/structalign/internal/testutil"
)

// makeCachePadStruct builds a *types.Struct programmatically that contains a
// field whose named type is from "golang.org/x/sys/cpu" named "CacheLinePad",
// satisfying HasCacheLinePad without needing a real import.
func makeCachePadStruct(t *testing.T) *types.Struct {
	t.Helper()
	// Synthetic cpu package and CacheLinePad type.
	cpuPkg := types.NewPackage("golang.org/x/sys/cpu", "cpu")
	underlying := types.NewStruct(nil, nil) // content irrelevant
	named := types.NewNamed(
		types.NewTypeName(token.NoPos, cpuPkg, "CacheLinePad", nil),
		underlying,
		nil)
	padField := types.NewField(token.NoPos, cpuPkg, "_", named, false)
	int64Field := types.NewField(token.NoPos, nil, "A", types.Typ[types.Int64], false)
	return types.NewStruct([]*types.Var{int64Field, padField}, nil)
}

func TestHasCacheLinePad_WithPad(t *testing.T) {
	st := makeCachePadStruct(t)
	assert.True(t, structfilter.HasCacheLinePad(st), "struct with CacheLinePad field should be detected")
}

func TestHasCacheLinePad_WithoutPad(t *testing.T) {
	// Plain struct with only primitive fields.
	field := types.NewField(token.NoPos, nil, "A", types.Typ[types.Int64], false)
	st := types.NewStruct([]*types.Var{field}, nil)
	assert.False(t, structfilter.HasCacheLinePad(st), "plain struct should not be detected")
}

func TestHasCacheLinePad_WrongPkgPath(t *testing.T) {
	// Named type named "CacheLinePad" but from the wrong package path.
	wrongPkg := types.NewPackage("some/other/pkg", "pkg")
	underlying := types.NewStruct(nil, nil)
	named := types.NewNamed(
		types.NewTypeName(token.NoPos, wrongPkg, "CacheLinePad", nil),
		underlying,
		nil)
	field := types.NewField(token.NoPos, nil, "_", named, false)
	st := types.NewStruct([]*types.Var{field}, nil)
	assert.False(t, structfilter.HasCacheLinePad(st), "same name but wrong package should not match")
}

const generatedSrc = `// Code generated by foo. DO NOT EDIT.
package sample

type Foo struct {
	A bool
	B int64
}
`

const plainSrc = `package sample

type Foo struct {
	A bool
	B int64
}
`

func TestInGeneratedFile_Generated(t *testing.T) {
	tgt := testutil.Target(t, generatedSrc)
	require.Len(t, tgt.Syntax, 1)

	obj := tgt.Types.Scope().Lookup("Foo")
	require.NotNil(t, obj, "Foo must be in scope")

	pos := obj.Pos()
	assert.True(t, structfilter.InGeneratedFile(tgt, pos), "Foo in generated file should return true")
}

func TestInGeneratedFile_NotGenerated(t *testing.T) {
	tgt := testutil.Target(t, plainSrc)
	require.Len(t, tgt.Syntax, 1)

	obj := tgt.Types.Scope().Lookup("Foo")
	require.NotNil(t, obj, "Foo must be in scope")

	pos := obj.Pos()
	assert.False(t, structfilter.InGeneratedFile(tgt, pos), "Foo in non-generated file should return false")
}

func TestHasCacheLinePad_WithAliasedPad(t *testing.T) {
	cpuPkg := types.NewPackage("golang.org/x/sys/cpu", "cpu")
	underlying := types.NewStruct(nil, nil)
	named := types.NewNamed(
		types.NewTypeName(token.NoPos, cpuPkg, "CacheLinePad", nil),
		underlying,
		nil)

	// Create an alias to named
	aliasPkg := types.NewPackage("my/pkg", "pkg")
	aliasTypeName := types.NewTypeName(token.NoPos, aliasPkg, "MyPadAlias", nil)
	alias := types.NewAlias(aliasTypeName, named)

	padField := types.NewField(token.NoPos, aliasPkg, "_", alias, false)
	st := types.NewStruct([]*types.Var{padField}, nil)
	assert.True(t, structfilter.HasCacheLinePad(st), "struct with aliased CacheLinePad field should be detected")
}
