package align_test

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"golang.org/x/tools/go/packages"

	"github.com/peczenyj/structalign/internal/align"
	"github.com/peczenyj/structalign/internal/sizes"
	"github.com/peczenyj/structalign/internal/testutil"
	"github.com/peczenyj/structalign/pkg/common"
)

const mixedSrc = `package sample

type Mixed struct {
	A bool
	B int64
	C bool
}

type Good struct {
	B int64
	A bool
	C bool
}
`

func TestFindingsReportsSuboptimalStruct(t *testing.T) {
	tgt := testutil.Target(t, mixedSrc)
	findings, err := align.New().Findings(tgt, common.Options{Patterns: []string{"Mixed"}})
	require.NoError(t, err)
	require.Len(t, findings, 1)
	assert.Equal(t, "Mixed", findings[0].Name)
	assert.NotEmpty(t, findings[0].Original)
	assert.NotEmpty(t, findings[0].Proposed)
}

func TestFindingsSkipsOptimalStruct(t *testing.T) {
	tgt := testutil.Target(t, mixedSrc)
	findings, err := align.New().Findings(tgt, common.Options{Patterns: []string{"Good"}})
	require.NoError(t, err)
	assert.Empty(t, findings)
}

func TestFindingsPopulatesSizes(t *testing.T) {
	tgt := testutil.Target(t, mixedSrc)
	findings, err := align.New().Findings(tgt, common.Options{Patterns: []string{"Mixed"}})
	require.NoError(t, err)
	require.Len(t, findings, 1)
	assert.Equal(t, int64(24), findings[0].OldSize, "OldSize should be 24 for Mixed")
	assert.Equal(t, int64(16), findings[0].NewSize, "NewSize should be 16 for Mixed")
}

const generatedSrc = `// Code generated by foo. DO NOT EDIT.
package sample

type Mixed struct {
	A bool
	B int64
	C bool
}
`

func TestFindingsSkipsGenerated(t *testing.T) {
	tgt := testutil.Target(t, generatedSrc)

	// By default (IncludeGenerated=false), generated structs are skipped.
	findings, err := align.New().Findings(tgt, common.Options{})
	require.NoError(t, err)
	assert.Empty(t, findings, "generated file structs should be skipped by default")

	// With IncludeGenerated=true, generated structs are included.
	findings, err = align.New().Findings(tgt, common.Options{IncludeGenerated: true})
	require.NoError(t, err)
	assert.Len(t, findings, 1, "generated file structs should be included when IncludeGenerated=true")
}

// loadPackageTarget loads the named package from dir using go/packages and
// returns a common.Target. It requires the module to be already set up in dir.
func loadPackageTarget(t *testing.T, dir string) common.Target {
	t.Helper()
	fset := token.NewFileSet()
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles |
			packages.NeedImports | packages.NeedDeps | packages.NeedTypes |
			packages.NeedTypesSizes | packages.NeedSyntax | packages.NeedTypesInfo,
		Fset: fset,
		Dir:  dir,
	}
	pkgs, err := packages.Load(cfg, ".")
	require.NoError(t, err, "packages.Load")
	require.Len(t, pkgs, 1, "expected exactly one package")
	p := pkgs[0]
	require.Empty(t, p.Errors, "package load errors")
	tgt := common.Target{
		PkgPath:   p.PkgPath,
		Fset:      p.Fset,
		Syntax:    p.Syntax,
		Types:     p.Types,
		TypesInfo: p.TypesInfo,
	}
	if p.TypesSizes != nil {
		tgt.Sizes = sizes.New(p.TypesSizes)
	}
	return tgt
}

// moduleRoot returns the repo root so we can reference go.mod for overlays.
func moduleRoot(t *testing.T) string {
	t.Helper()
	// Walk up from this test file's directory to find go.mod.
	dir, err := filepath.Abs(".")
	require.NoError(t, err)
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("could not find go.mod")
		}
		dir = parent
	}
}

const cachePadSrc = `package sample

import "golang.org/x/sys/cpu"

// WithPad has a cpu.CacheLinePad field AND a suboptimal layout (bool before int64).
type WithPad struct {
	A    bool
	_    cpu.CacheLinePad
	B    int64
}
`

func TestFindingsSkipsCachePadded(t *testing.T) {
	root := moduleRoot(t)

	// Create a temp directory that is part of the module (no separate go.mod).
	// Place it under internal/align/testdata/ which the go tool can see.
	tmpDir := t.TempDir()
	err := os.WriteFile(filepath.Join(tmpDir, "types.go"), []byte(cachePadSrc), 0o600)
	require.NoError(t, err)

	// Copy the module's go.mod/go.sum so go/packages can resolve deps.
	// We need a proper module: symlink or copy go.mod into a sibling dir
	// with a replace directive isn't needed if we put our file inside the
	// existing module. Instead, create a tiny overlay module and use
	// GOFLAGS=-mod=mod or just load from the module root with an overlay.
	//
	// Simplest approach: create a temp dir *inside* the module, write the
	// file there, and load it as a sub-package. But the go tool needs a
	// package declaration consistent with the module path...
	//
	// Cleanest: write to a known test path and restore it.
	// We use a unique package name to avoid collisions.
	testPkgDir := filepath.Join(root, "internal", "align", "_cachepadtest")
	if err := os.MkdirAll(testPkgDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(testPkgDir) })

	src := `package cachepadtest

import "golang.org/x/sys/cpu"

// WithPad has a cpu.CacheLinePad field AND a suboptimal layout.
// The bool fields before int64 cause the analyzer to flag it, but the cpu pad
// field means we should be able to skip it with SkipCachePadded=true.
type WithPad struct {
	A bool
	B int64
	C bool
	_ cpu.CacheLinePad
}
`
	err = os.WriteFile(filepath.Join(testPkgDir, "types.go"), []byte(src), 0o600)
	require.NoError(t, err)
	_ = tmpDir // no longer needed

	tgt := loadPackageTarget(t, testPkgDir)

	// Without SkipCachePadded, WithPad should be reported (it has a suboptimal layout).
	findings, ferr := align.New().Findings(tgt, common.Options{})
	require.NoError(t, ferr)
	assert.NotEmpty(t, findings, "WithPad should be reported without SkipCachePadded")

	// With SkipCachePadded=true, WithPad should be silently skipped.
	findings, ferr = align.New().Findings(tgt, common.Options{SkipCachePadded: true})
	require.NoError(t, ferr)
	assert.Empty(t, findings, "WithPad should be skipped when SkipCachePadded=true")
}

func TestFindingsSkipsAnonymousCachePadded(t *testing.T) {
	root := moduleRoot(t)
	testPkgDir := filepath.Join(root, "internal", "align", "_anoncachepadtest")
	if err := os.MkdirAll(testPkgDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	t.Cleanup(func() { os.RemoveAll(testPkgDir) })

	src := `package anoncachepadtest

import "golang.org/x/sys/cpu"

var V = struct {
	A bool
	B int64
	C bool
	_ cpu.CacheLinePad
}{A: true, B: 1, C: true}
`
	err := os.WriteFile(filepath.Join(testPkgDir, "types.go"), []byte(src), 0o600)
	require.NoError(t, err)

	tgt := loadPackageTarget(t, testPkgDir)

	// Without SkipCachePadded, the anonymous struct should be reported.
	findings, ferr := align.New().Findings(tgt, common.Options{})
	require.NoError(t, ferr)
	assert.NotEmpty(t, findings, "Anonymous struct should be reported without SkipCachePadded")

	// With SkipCachePadded=true, the anonymous struct should be silently skipped.
	findings, ferr = align.New().Findings(tgt, common.Options{SkipCachePadded: true})
	require.NoError(t, ferr)
	assert.Empty(t, findings, "Anonymous struct should be skipped when SkipCachePadded=true")
}
