name: CI

on:
  push:
    branches: [main, devel, "release/**", "hotfix/**"]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: ["1.25.0", "stable"]
    name: build (go ${{ matrix.go-version }})
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go-version }}

      - uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.13.0

      - name: Lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: v2.12.2

      - name: Install go-consistent
        run: go install github.com/quasilyte/go-consistent@v0.6.2

      - name: Consistency check
        run: task consistent

      - name: Build
        run: go build ./...

      - name: Test
        run: task test:coverage

      - name: Upload coverage to Codecov
        if: matrix.go-version == 'stable'
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: peczenyj/structalign
          files: ./coverage.txt
          fail_ci_if_error: false

      - name: Smoke test
        run: task smoke
